import os
import httpx
from jose import jwt, JWTError
from fastapi import HTTPException, status
from typing import Optional, Dict

# Configuration
SUPABASE_URL = os.getenv("SUPABASE_URL")
if not SUPABASE_URL:
    # Fallback to project ref if available in env, otherwise error
    PROJECT_REF = os.getenv("SUPABASE_PROJECT_REF", "eswlocdooykyaxqyphwu")
    SUPABASE_URL = f"https://{PROJECT_REF}.supabase.co"

SUPABASE_ANON_KEY = os.getenv("SUPABASE_PUBLIC_KEY") or os.getenv("SUPABASE_KEY")

JWKS_URL = f"{SUPABASE_URL}/auth/v1/certs"
ISSUER = f"{SUPABASE_URL}/auth/v1"

class SupabaseJWTVerifier:
    def __init__(self):
        self.jwks = {"keys": []}
        self.last_fetched = 0

    async def fetch_jwks(self):
        try:
            async with httpx.AsyncClient() as client:
                headers = {}
                anon_key = os.getenv("SUPABASE_PUBLIC_KEY") or os.getenv("SUPABASE_KEY")
                if anon_key:
                    headers["apikey"] = anon_key
                # Also need Authorization for JWT if it requires it, but usually just apikey is needed for fetching JWKS
                response = await client.get(JWKS_URL, headers=headers)
                response.raise_for_status()
                self.jwks = response.json()
        except Exception as e:
            print(f"Error fetching Supabase JWKS: {e}")
            self.jwks = {"keys": []}
            # We don't raise here anymore; the caller will handle missing keys

    async def verify_token(self, token: str) -> Optional[Dict]:
        try:
            # Check if it's a valid JWT and examine header
            unverified_header = jwt.get_unverified_header(token)
            kid = unverified_header.get("kid")
            
            if not kid:
                # It's a local token generated by FastAPI (HS256)
                # This handles tokens from login/google-login routes
                secret = os.getenv("JWT_SECRET", "s8xJ29sK!2ksl9aJsk29KslsksK2ksl29")
                try:
                    payload = jwt.decode(token, secret, algorithms=["HS256"])
                    return payload
                except JWTError as e:
                    # If it's not a local token, it might be a Supabase HS256 token 
                    # signed with the project's secret. But the requirements suggest 
                    # we are swapping Supabase tokens for local ones.
                    print(f"Local HS256 Verification Failed: {e}")
                    return None

            # Find the correct key in JWKS for Supabase tokens (RS256)
            if not self.jwks or not self.jwks.get("keys"):
                try:
                    await self.fetch_jwks()
                except Exception as e:
                    print(f"JWKS Fetch Failed: {e}")
                    # If fetch fails, we can't verify RS256 tokens.
                    return None

            key = None
            if self.jwks and "keys" in self.jwks:
                for jwk in self.jwks["keys"]:
                    if jwk.get("kid") == kid:
                        key = jwk
                        break

            if not key:
                # Key not found, try refreshing JWKS once
                try:
                    await self.fetch_jwks()
                except:
                    pass

                if self.jwks and "keys" in self.jwks:
                    for jwk in self.jwks["keys"]:
                        if jwk.get("kid") == kid:
                            key = jwk
                            break
                
                if not key:
                    raise JWTError(f"Could not find public key with kid: {kid}")

            # Decode and verify Supabase token
            payload = jwt.decode(
                token,
                key,
                algorithms=["RS256"],
                audience="authenticated",  # Supabase default aud
                issuer=ISSUER,
                options={
                    "verify_aud": True,
                    "verify_iss": True,
                    "verify_exp": True,
                    "verify_iat": False,
                }
            )
            return payload

        except JWTError as e:
            print(f"JWT Verification Error: {e}")
            return None
        except Exception as e:
            print(f"Unexpected error during token verification: {e}")
            return None

# Singleton instance
verifier = SupabaseJWTVerifier()
